public class Main {
    
    public static void main(String[] args) {
        String Nama = "Alvin";
        System.out.println("nama saya adalah "+Nama);
        String alamat = "Tapalang";
        System.out.println("Alamat saya ada di "+alamat);
        int umur = 17;
        System.out.println("umur saya adalah "+umur + "Tahun");
        String handphone = "082216747582";
        System.out.println("nomor Handphone saya : "+handphone);
    }
    
}
